In [1]:
import tensorflow
from tensorflow import keras
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from matplotlib import pyplot
from keras.callbacks import EarlyStopping
import time

Using TensorFlow backend.

In [105]:
#Loading Data Into Data Frame

df = pd.read_csv("data.csv") 
df.head(5)                                 # Display the top 5 rows

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500

In [106]:
df.count()

Make                 11914
Model                11914
Year                 11914
Engine Fuel Type     11911
Engine HP            11845
Engine Cylinders     11884
Transmission Type    11914
Driven_Wheels        11914
Number of Doors      11908
Market Category       8172
Vehicle Size         11914
Vehicle Style        11914
highway MPG          11914
city mpg             11914
Popularity           11914
MSRP                 11914
dtype: int64

In [107]:
df = df.drop_duplicates()      #Drop duplicate row

In [108]:
df.count()

Make                 11199
Model                11199
Year                 11199
Engine Fuel Type     11196
Engine HP            11130
Engine Cylinders     11169
Transmission Type    11199
Driven_Wheels        11199
Number of Doors      11193
Market Category       7823
Vehicle Size         11199
Vehicle Style        11199
highway MPG          11199
city mpg             11199
Popularity           11199
MSRP                 11199
dtype: int64

In [109]:
#Dropping the missing and null values

print(df.isnull().sum())         #count the number of missing and null values

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3376
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [110]:
df = df.dropna()    #Drop the missing values.
df.count()          #Count the number of rows after dropping the missing and null values

Make                 7735
Model                7735
Year                 7735
Engine Fuel Type     7735
Engine HP            7735
Engine Cylinders     7735
Transmission Type    7735
Driven_Wheels        7735
Number of Doors      7735
Market Category      7735
Vehicle Size         7735
Vehicle Style        7735
highway MPG          7735
city mpg             7735
Popularity           7735
MSRP                 7735
dtype: int64

In [111]:
print(df.isnull().sum())   #Check if there are some still missing or null values left

Make                 0
Model                0
Year                 0
Engine Fuel Type     0
Engine HP            0
Engine Cylinders     0
Transmission Type    0
Driven_Wheels        0
Number of Doors      0
Market Category      0
Vehicle Size         0
Vehicle Style        0
highway MPG          0
city mpg             0
Popularity           0
MSRP                 0
dtype: int64

In [112]:
df['MSRP'] = (df['MSRP'] >= 40000).astype(int)
df.head(5)

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,1
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,1
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,0
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,0
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,0

In [113]:
for col in df.columns:
    df = df[df[col].notnull()]

In [114]:
string_col = ['Make', 'Model', 'Engine Fuel Type', 'Transmission Type', 'Driven_Wheels', 'Market Category', 'Vehicle Size', 'Vehicle Style']
for col in string_col:
    df[col] = df[col].astype('category')
    df[col] = df[col].cat.codes

df.head(5)

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,4,1,2011,6,335.0,6.0,3,3,2.0,37,0,8,26,19,3916,1
1,4,0,2011,6,300.0,6.0,3,3,2.0,66,0,6,28,19,3916,1
2,4,0,2011,6,300.0,6.0,3,3,2.0,63,0,8,28,20,3916,0
3,4,0,2011,6,230.0,6.0,3,3,2.0,66,0,8,28,18,3916,0
4,4,0,2011,6,230.0,6.0,3,3,2.0,62,0,6,28,18,3916,0

In [115]:
feature_cols = ['Make', 'Model', 'Year', 'Engine Fuel Type','Engine HP','Engine Cylinders','Transmission Type', 'Driven_Wheels', 'Vehicle Size', 'Vehicle Style', 'highway MPG', 'city mpg', 'Popularity']
X = df[feature_cols] # Features
y = df.MSRP # Target variable

In [116]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, shuffle=False)

In [117]:
X_train

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity
0,4,1,2011,6,335.0,6.0,3,3,0,8,26,19,3916
1,4,0,2011,6,300.0,6.0,3,3,0,6,28,19,3916
2,4,0,2011,6,300.0,6.0,3,3,0,8,28,20,3916
3,4,0,2011,6,230.0,6.0,3,3,0,8,28,18,3916
4,4,0,2011,6,230.0,6.0,3,3,0,6,28,18,3916
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8242,23,533,2015,5,240.0,4.0,1,0,0,3,30,21,258
8243,23,533,2015,5,240.0,4.0,1,0,0,1,30,21,258
8244,23,533,2015,5,240.0,4.0,1,0,0,3,30,21,258
8246,23,533,2015,5,240.0,4.0,1,0,0,3,30,21,258
8247,23,533,2015,5,240.0,4.0,1,0,0,1,30,21,258

In [118]:
X_test

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity
8248,23,533,2015,5,240.0,4.0,1,0,0,3,30,21,258
8249,23,533,2015,5,240.0,4.0,1,0,0,1,30,21,258
8251,23,533,2015,5,240.0,4.0,1,0,0,3,30,21,258
8252,23,533,2015,5,240.0,4.0,1,0,0,3,30,21,258
8253,23,533,2015,5,240.0,4.0,1,0,0,3,30,21,258
...,...,...,...,...,...,...,...,...,...,...,...,...,...
11909,0,703,2012,6,300.0,6.0,1,0,2,2,23,16,204
11910,0,703,2012,6,300.0,6.0,1,0,2,2,23,16,204
11911,0,703,2012,6,300.0,6.0,1,0,2,2,23,16,204
11912,0,703,2013,5,300.0,6.0,1,0,2,2,23,16,204
11913,25,704,2006,7,221.0,6.0,1,2,2,14,26,17,61

In [119]:
model=keras.models.Sequential([
    keras.layers.Dense(64, input_dim = X_train.shape[1], activation='tanh'),  
    keras.layers.Dropout(0.3),
    
    keras.layers.Dense(units=32, activation='tanh'), 
    keras.layers.Dropout(0.2),
    
    keras.layers.Dense(units=1, activation="sigmoid"),
],name="Initial_model",)
model.summary()

Model: "Initial_model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_12 (Dense)             (None, 64)                896
_________________________________________________________________
dropout_8 (Dropout)          (None, 64)                0
_________________________________________________________________
dense_13 (Dense)             (None, 32)                2080
_________________________________________________________________
dropout_9 (Dropout)          (None, 32)                0
_________________________________________________________________
dense_14 (Dense)             (None, 1)                 33
=================================================================
Total params: 3,009
Trainable params: 3,009
Non-trainable params: 0
_________________________________________________________________

In [120]:
learning_rate = 0.01
optimizer = keras.optimizers.Adam(lr=learning_rate)

In [121]:
model.compile(optimizer=optimizer,
            loss='binary_crossentropy', metrics=['accuracy'])

In [122]:
early_stopping_monitor = EarlyStopping(
    monitor='val_loss',
    min_delta=0,
    patience=100,
    verbose=0,
    mode='auto',
    baseline=None,
    restore_best_weights=True
)

In [123]:
start = time.clock() 
history = model.fit(X_train, y_train, epochs=1000, batch_size=512, validation_data=(X_test, y_test), verbose=1, callbacks=[early_stopping_monitor])
end = time.clock()

C:\Users\ASUS\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  """Entry point for launching an IPython kernel.

Train on 5414 samples, validate on 2321 samples
Epoch 1/1000
5414/5414 [==============================] - 1s 166us/sample - loss: 0.7166 - accuracy: 0.5960 - val_loss: 0.6331 - val_accuracy: 0.6691
Epoch 2/1000
5414/5414 [==============================] - 0s 13us/sample - loss: 0.6442 - accuracy: 0.6269 - val_loss: 0.5896 - val_accuracy: 0.6863
Epoch 3/1000
5414/5414 [==============================] - 0s 14us/sample - loss: 0.6198 - accuracy: 0.6600 - val_loss: 0.5211 - val_accuracy: 0.8044
Epoch 4/1000
5414/5414 [==============================] - 0s 13us/sample - loss: 0.5733 - accuracy: 0.6984 - val_loss: 0.5215 - val_accuracy: 0.7346
Epoch 5/1000
5414/5414 [==============================] - 0s 13us/sample - loss: 0.5498 - accuracy: 0.7307 - val_loss: 0.4937 - val_accuracy: 0.7376
Epoch 6/1000
5414/5414 [==============================] - 0s 12us/sample - loss: 0.5335 - accuracy: 0.7307 - val_loss: 0.4636 - val_accuracy: 0.7893
Epoch 7/1000
5414/5414 [==============================] - 0s 11us/sample - loss: 0.5439 - accuracy: 0.7414 - val_loss: 0.5290 - val_accuracy: 0.7734
Epoch 8/1000
5414/5414 [==============================] - 0s 14us/sample - loss: 0.5584 - accuracy: 0.7076 - val_loss: 0.5937 - val_accuracy: 0.7238
Epoch 9/1000
5414/5414 [==============================] - 0s 14us/sample - loss: 0.5574 - accuracy: 0.7024 - val_loss: 0.5617 - val_accuracy: 0.7419
Epoch 10/1000
5414/5414 [==============================] - 0s 12us/sample - loss: 0.5511 - accuracy: 0.7261 - val_loss: 0.4986 - val_accuracy: 0.7785
Epoch 11/1000
5414/5414 [==============================] - 0s 10us/sample - loss: 0.5508 - accuracy: 0.7327 - val_loss: 0.5197 - val_accuracy: 0.7777
Epoch 12/1000
5414/5414 [==============================] - 0s 13us/sample - loss: 0.5087 - accuracy: 0.7652 - val_loss: 0.4893 - val_accuracy: 0.7536
Epoch 13/1000
5414/5414 [==============================] - 0s 18us/sample - loss: 0.5154 - accuracy: 0.7416 - val_loss: 0.4923 - val_accuracy: 0.7755
Epoch 14/1000
5414/5414 [==============================] - 0s 15us/sample - loss: 0.5015 - accuracy: 0.7654 - val_loss: 0.4724 - val_accuracy: 0.7897
Epoch 15/1000
5414/5414 [==============================] - 0s 13us/sample - loss: 0.4891 - accuracy: 0.7795 - val_loss: 0.4534 - val_accuracy: 0.7803
Epoch 16/1000
5414/5414 [==============================] - 0s 12us/sample - loss: 0.4818 - accuracy: 0.7833 - val_loss: 0.4913 - val_accuracy: 0.8014
Epoch 17/1000
5414/5414 [==============================] - 0s 12us/sample - loss: 0.4702 - accuracy: 0.7889 - val_loss: 0.4822 - val_accuracy: 0.7880
Epoch 18/1000
5414/5414 [==============================] - 0s 11us/sample - loss: 0.5257 - accuracy: 0.7259 - val_loss: 0.4615 - val_accuracy: 0.7820
Epoch 19/1000
5414/5414 [==============================] - 0s 11us/sample - loss: 0.4731 - accuracy: 0.7789 - val_loss: 0.4689 - val_accuracy: 0.7725
Epoch 20/1000
5414/5414 [==============================] - 0s 15us/sample - loss: 0.4811 - accuracy: 0.7649 - val_loss: 0.4879 - val_accuracy: 0.7277
Epoch 21/1000
5414/5414 [==============================] - 0s 12us/sample - loss: 0.5142 - accuracy: 0.7553 - val_loss: 0.5262 - val_accuracy: 0.8121
Epoch 22/1000
5414/5414 [==============================] - 0s 13us/sample - loss: 0.5077 - accuracy: 0.7617 - val_loss: 0.4985 - val_accuracy: 0.7036
Epoch 23/1000
5414/5414 [==============================] - 0s 11us/sample - loss: 0.4829 - accuracy: 0.7569 - val_loss: 0.4507 - val_accuracy: 0.7880
Epoch 24/1000
5414/5414 [==============================] - 0s 12us/sample - loss: 0.4683 - accuracy: 0.7796 - val_loss: 0.4270 - val_accuracy: 0.8134
Epoch 25/1000
5414/5414 [==============================] - 0s 12us/sample - loss: 0.4766 - accuracy: 0.7808 - val_loss: 0.5008 - val_accuracy: 0.7906
Epoch 26/1000
5414/5414 [==============================] - 0s 13us/sample - loss: 0.4814 - accuracy: 0.7793 - val_loss: 0.5746 - val_accuracy: 0.7368
Epoch 27/1000
5414/5414 [==============================] - 0s 11us/sample - loss: 0.4985 - accuracy: 0.7676 - val_loss: 0.5578 - val_accuracy: 0.7622
Epoch 28/1000
5414/5414 [==============================] - 0s 12us/sample - loss: 0.4901 - accuracy: 0.7806 - val_loss: 0.5437 - val_accuracy: 0.7751
Epoch 29/1000
5414/5414 [==============================] - 0s 13us/sample - loss: 0.5120 - accuracy: 0.7627 - val_loss: 0.5001 - val_accuracy: 0.7536
Epoch 30/1000
5414/5414 [==============================] - 0s 11us/sample - loss: 0.4967 - accuracy: 0.7470 - val_loss: 0.4833 - val_accuracy: 0.7885
Epoch 31/1000
5414/5414 [==============================] - 0s 13us/sample - loss: 0.5103 - accuracy: 0.7486 - val_loss: 0.4735 - val_accuracy: 0.8156
Epoch 32/1000
5414/5414 [==============================] - 0s 12us/sample - loss: 0.4757 - accuracy: 0.8029 - val_loss: 0.4961 - val_accuracy: 0.7811
Epoch 33/1000
5414/5414 [==============================] - 0s 11us/sample - loss: 0.4978 - accuracy: 0.7728 - val_loss: 0.4899 - val_accuracy: 0.8061
Epoch 34/1000
5414/5414 [==============================] - 0s 13us/sample - loss: 0.4871 - accuracy: 0.7802 - val_loss: 0.5077 - val_accuracy: 0.7755
Epoch 35/1000
5414/5414 [==============================] - 0s 11us/sample - loss: 0.4961 - accuracy: 0.7739 - val_loss: 0.5084 - val_accuracy: 0.7643
Epoch 36/1000
5414/5414 [==============================] - 0s 13us/sample - loss: 0.4815 - accuracy: 0.7804 - val_loss: 0.5035 - val_accuracy: 0.7708
Epoch 37/1000
5414/5414 [==============================] - 0s 14us/sample - loss: 0.4751 - accuracy: 0.7928 - val_loss: 0.4606 - val_accuracy: 0.8078
Epoch 38/1000
5414/5414 [==============================] - 0s 12us/sample - loss: 0.4597 - accuracy: 0.7941 - val_loss: 0.4812 - val_accuracy: 0.8087
Epoch 39/1000
5414/5414 [==============================] - 0s 12us/sample - loss: 0.5045 - accuracy: 0.7651 - val_loss: 0.4830 - val_accuracy: 0.8001
Epoch 40/1000
5414/5414 [==============================] - 0s 12us/sample - loss: 0.5211 - accuracy: 0.7335 - val_loss: 0.4768 - val_accuracy: 0.7432
Epoch 41/1000
5414/5414 [==============================] - 0s 17us/sample - loss: 0.4818 - accuracy: 0.7641 - val_loss: 0.4961 - val_accuracy: 0.7643
Epoch 42/1000
5414/5414 [==============================] - 0s 17us/sample - loss: 0.4721 - accuracy: 0.7687 - val_loss: 0.4652 - val_accuracy: 0.7820
Epoch 43/1000
5414/5414 [==============================] - 0s 14us/sample - loss: 0.4838 - accuracy: 0.7689 - val_loss: 0.5581 - val_accuracy: 0.7880
Epoch 44/1000
5414/5414 [==============================] - 0s 11us/sample - loss: 0.4992 - accuracy: 0.7684 - val_loss: 0.5319 - val_accuracy: 0.7639
Epoch 45/1000
5414/5414 [==============================] - 0s 11us/sample - loss: 0.4902 - accuracy: 0.7645 - val_loss: 0.5210 - val_accuracy: 0.8065
Epoch 46/1000
5414/5414 [==============================] - 0s 13us/sample - loss: 0.5069 - accuracy: 0.7776 - val_loss: 0.5094 - val_accuracy: 0.7294
Epoch 47/1000
5414/5414 [==============================] - 0s 11us/sample - loss: 0.5071 - accuracy: 0.7693 - val_loss: 0.4845 - val_accuracy: 0.7075
Epoch 48/1000
5414/5414 [==============================] - 0s 13us/sample - loss: 0.4960 - accuracy: 0.7543 - val_loss: 0.5245 - val_accuracy: 0.6751
Epoch 49/1000
5414/5414 [==============================] - 0s 12us/sample - loss: 0.5534 - accuracy: 0.7165 - val_loss: 0.5383 - val_accuracy: 0.7764
Epoch 50/1000
5414/5414 [==============================] - 0s 11us/sample - loss: 0.5519 - accuracy: 0.6936 - val_loss: 0.5121 - val_accuracy: 0.7087
Epoch 51/1000
5414/5414 [==============================] - 0s 11us/sample - loss: 0.4830 - accuracy: 0.7645 - val_loss: 0.5254 - val_accuracy: 0.7467
Epoch 52/1000
5414/5414 [==============================] - 0s 13us/sample - loss: 0.5309 - accuracy: 0.7518 - val_loss: 0.5406 - val_accuracy: 0.7669
Epoch 53/1000
5414/5414 [==============================] - 0s 12us/sample - loss: 0.5213 - accuracy: 0.7567 - val_loss: 0.5216 - val_accuracy: 0.7648
Epoch 54/1000
5414/5414 [==============================] - 0s 11us/sample - loss: 0.4930 - accuracy: 0.7747 - val_loss: 0.4848 - val_accuracy: 0.7436
Epoch 55/1000

5414/5414 [==============================] - 0s 15us/sample - loss: 0.4755 - accuracy: 0.7710 - val_loss: 0.5026 - val_accuracy: 0.7704
Epoch 56/1000
5414/5414 [==============================] - 0s 13us/sample - loss: 0.4802 - accuracy: 0.7806 - val_loss: 0.5105 - val_accuracy: 0.7639
Epoch 57/1000
5414/5414 [==============================] - 0s 11us/sample - loss: 0.4800 - accuracy: 0.7772 - val_loss: 0.4999 - val_accuracy: 0.7691
Epoch 58/1000
5414/5414 [==============================] - 0s 14us/sample - loss: 0.4738 - accuracy: 0.7833 - val_loss: 0.4968 - val_accuracy: 0.7798
Epoch 59/1000
5414/5414 [==============================] - 0s 11us/sample - loss: 0.4604 - accuracy: 0.7867 - val_loss: 0.4566 - val_accuracy: 0.7574
Epoch 60/1000
5414/5414 [==============================] - 0s 13us/sample - loss: 0.4590 - accuracy: 0.7922 - val_loss: 0.4923 - val_accuracy: 0.8057
Epoch 61/1000
5414/5414 [==============================] - 0s 12us/sample - loss: 0.4984 - accuracy: 0.7647 - val_loss: 0.4626 - val_accuracy: 0.7932
Epoch 62/1000
5414/5414 [==============================] - 0s 11us/sample - loss: 0.4885 - accuracy: 0.7484 - val_loss: 0.5024 - val_accuracy: 0.7303
Epoch 63/1000
5414/5414 [==============================] - 0s 12us/sample - loss: 0.4556 - accuracy: 0.7922 - val_loss: 0.5468 - val_accuracy: 0.7609
Epoch 64/1000
5414/5414 [==============================] - 0s 12us/sample - loss: 0.4823 - accuracy: 0.7852 - val_loss: 0.5083 - val_accuracy: 0.7497
Epoch 65/1000
5414/5414 [==============================] - 0s 11us/sample - loss: 0.4760 - accuracy: 0.7832 - val_loss: 0.4668 - val_accuracy: 0.7863
Epoch 66/1000
5414/5414 [==============================] - 0s 12us/sample - loss: 0.4711 - accuracy: 0.7865 - val_loss: 0.4813 - val_accuracy: 0.7471
Epoch 67/1000
5414/5414 [==============================] - 0s 13us/sample - loss: 0.4620 - accuracy: 0.7896 - val_loss: 0.4733 - val_accuracy: 0.7867
Epoch 68/1000
5414/5414 [==============================] - 0s 11us/sample - loss: 0.4681 - accuracy: 0.7686 - val_loss: 0.4450 - val_accuracy: 0.7997
Epoch 69/1000
5414/5414 [==============================] - 0s 13us/sample - loss: 0.4558 - accuracy: 0.7841 - val_loss: 0.5001 - val_accuracy: 0.7053
Epoch 70/1000
5414/5414 [==============================] - 0s 12us/sample - loss: 0.4819 - accuracy: 0.7736 - val_loss: 0.5180 - val_accuracy: 0.7897
Epoch 71/1000
5414/5414 [==============================] - 0s 13us/sample - loss: 0.4736 - accuracy: 0.7787 - val_loss: 0.5032 - val_accuracy: 0.7811
Epoch 72/1000
5414/5414 [==============================] - 0s 11us/sample - loss: 0.4742 - accuracy: 0.7939 - val_loss: 0.5324 - val_accuracy: 0.7717
Epoch 73/1000
5414/5414 [==============================] - 0s 13us/sample - loss: 0.4596 - accuracy: 0.7893 - val_loss: 0.5110 - val_accuracy: 0.7738
Epoch 74/1000
5414/5414 [==============================] - 0s 11us/sample - loss: 0.4725 - accuracy: 0.7772 - val_loss: 0.4782 - val_accuracy: 0.7863
Epoch 75/1000
5414/5414 [==============================] - 0s 11us/sample - loss: 0.4547 - accuracy: 0.7920 - val_loss: 0.5080 - val_accuracy: 0.8065
Epoch 76/1000
5414/5414 [==============================] - 0s 13us/sample - loss: 0.4807 - accuracy: 0.7920 - val_loss: 0.5111 - val_accuracy: 0.7816
Epoch 77/1000
5414/5414 [==============================] - 0s 11us/sample - loss: 0.4955 - accuracy: 0.7686 - val_loss: 0.5217 - val_accuracy: 0.7850
Epoch 78/1000
5414/5414 [==============================] - 0s 13us/sample - loss: 0.5198 - accuracy: 0.7610 - val_loss: 0.4920 - val_accuracy: 0.7673
Epoch 79/1000
5414/5414 [==============================] - 0s 12us/sample - loss: 0.5063 - accuracy: 0.7591 - val_loss: 0.5129 - val_accuracy: 0.7424
Epoch 80/1000
5414/5414 [==============================] - 0s 11us/sample - loss: 0.5042 - accuracy: 0.7569 - val_loss: 0.5114 - val_accuracy: 0.8044
Epoch 81/1000
5414/5414 [==============================] - 0s 13us/sample - loss: 0.5415 - accuracy: 0.7394 - val_loss: 0.5589 - val_accuracy: 0.7424
Epoch 82/1000
5414/5414 [==============================] - 0s 12us/sample - loss: 0.5122 - accuracy: 0.7554 - val_loss: 0.5070 - val_accuracy: 0.7501
Epoch 83/1000
5414/5414 [==============================] - 0s 13us/sample - loss: 0.4637 - accuracy: 0.7815 - val_loss: 0.4966 - val_accuracy: 0.7204
Epoch 84/1000
5414/5414 [==============================] - 0s 11us/sample - loss: 0.4622 - accuracy: 0.7820 - val_loss: 0.4823 - val_accuracy: 0.7497
Epoch 85/1000
5414/5414 [==============================] - 0s 12us/sample - loss: 0.4689 - accuracy: 0.7697 - val_loss: 0.5080 - val_accuracy: 0.7729
Epoch 86/1000
5414/5414 [==============================] - 0s 13us/sample - loss: 0.4765 - accuracy: 0.7881 - val_loss: 0.5754 - val_accuracy: 0.7510
Epoch 87/1000
5414/5414 [==============================] - 0s 11us/sample - loss: 0.5024 - accuracy: 0.7632 - val_loss: 0.5166 - val_accuracy: 0.7393
Epoch 88/1000
5414/5414 [==============================] - 0s 12us/sample - loss: 0.4876 - accuracy: 0.7665 - val_loss: 0.4476 - val_accuracy: 0.7902
Epoch 89/1000
5414/5414 [==============================] - 0s 18us/sample - loss: 0.4566 - accuracy: 0.7887 - val_loss: 0.5491 - val_accuracy: 0.7561
Epoch 90/1000
5414/5414 [==============================] - 0s 21us/sample - loss: 0.4835 - accuracy: 0.7582 - val_loss: 0.4920 - val_accuracy: 0.7187
Epoch 91/1000
5414/5414 [==============================] - 0s 22us/sample - loss: 0.4962 - accuracy: 0.7394 - val_loss: 0.4880 - val_accuracy: 0.7656
Epoch 92/1000
5414/5414 [==============================] - 0s 19us/sample - loss: 0.4762 - accuracy: 0.7806 - val_loss: 0.4714 - val_accuracy: 0.7785
Epoch 93/1000
5414/5414 [==============================] - 0s 14us/sample - loss: 0.4640 - accuracy: 0.7784 - val_loss: 0.4713 - val_accuracy: 0.8014
Epoch 94/1000
5414/5414 [==============================] - 0s 14us/sample - loss: 0.4946 - accuracy: 0.7401 - val_loss: 0.4594 - val_accuracy: 0.8001
Epoch 95/1000
5414/5414 [==============================] - 0s 11us/sample - loss: 0.4806 - accuracy: 0.7687 - val_loss: 0.4859 - val_accuracy: 0.7428
Epoch 96/1000
5414/5414 [==============================] - 0s 11us/sample - loss: 0.4983 - accuracy: 0.7571 - val_loss: 0.4929 - val_accuracy: 0.7199
Epoch 97/1000
5414/5414 [==============================] - 0s 12us/sample - loss: 0.4968 - accuracy: 0.7734 - val_loss: 0.5396 - val_accuracy: 0.7958
Epoch 98/1000
5414/5414 [==============================] - 0s 12us/sample - loss: 0.4849 - accuracy: 0.7833 - val_loss: 0.5297 - val_accuracy: 0.7915
Epoch 99/1000
5414/5414 [==============================] - 0s 11us/sample - loss: 0.4784 - accuracy: 0.7959 - val_loss: 0.5381 - val_accuracy: 0.8005
Epoch 100/1000
5414/5414 [==============================] - 0s 13us/sample - loss: 0.4672 - accuracy: 0.8000 - val_loss: 0.4633 - val_accuracy: 0.8083
Epoch 101/1000
5414/5414 [==============================] - 0s 11us/sample - loss: 0.4615 - accuracy: 0.7922 - val_loss: 0.4969 - val_accuracy: 0.8065
Epoch 102/1000
5414/5414 [==============================] - 0s 11us/sample - loss: 0.4595 - accuracy: 0.7867 - val_loss: 0.4554 - val_accuracy: 0.7915
Epoch 103/1000
5414/5414 [==============================] - 0s 12us/sample - loss: 0.4800 - accuracy: 0.7867 - val_loss: 0.5318 - val_accuracy: 0.8044
Epoch 104/1000
5414/5414 [==============================] - 0s 14us/sample - loss: 0.4842 - accuracy: 0.7913 - val_loss: 0.5009 - val_accuracy: 0.8109
Epoch 105/1000
5414/5414 [==============================] - 0s 11us/sample - loss: 0.4619 - accuracy: 0.7893 - val_loss: 0.5107 - val_accuracy: 0.7816
Epoch 106/1000
5414/5414 [==============================] - 0s 13us/sample - loss: 0.4509 - accuracy: 0.7946 - val_loss: 0.5203 - val_accuracy: 0.8091
Epoch 107/1000
5414/5414 [==============================] - 0s 11us/sample - loss: 0.4677 - accuracy: 0.7896 - val_loss: 0.5236 - val_accuracy: 0.7389
Epoch 108/1000
5414/5414 [==============================] - 0s 11us/sample - loss: 0.4557 - accuracy: 0.7880 - val_loss: 0.5260 - val_accuracy: 0.7975
Epoch 109/1000

5414/5414 [==============================] - 0s 13us/sample - loss: 0.4641 - accuracy: 0.8050 - val_loss: 0.5044 - val_accuracy: 0.7570
Epoch 110/1000
5414/5414 [==============================] - 0s 15us/sample - loss: 0.4659 - accuracy: 0.8062 - val_loss: 0.5091 - val_accuracy: 0.7932
Epoch 111/1000
5414/5414 [==============================] - 0s 21us/sample - loss: 0.4842 - accuracy: 0.7841 - val_loss: 0.4810 - val_accuracy: 0.7027
Epoch 112/1000
5414/5414 [==============================] - 0s 24us/sample - loss: 0.5075 - accuracy: 0.7554 - val_loss: 0.4529 - val_accuracy: 0.7846
Epoch 113/1000
5414/5414 [==============================] - 0s 22us/sample - loss: 0.4560 - accuracy: 0.7881 - val_loss: 0.4612 - val_accuracy: 0.7678
Epoch 114/1000
5414/5414 [==============================] - 0s 22us/sample - loss: 0.4558 - accuracy: 0.7865 - val_loss: 0.4593 - val_accuracy: 0.7656
Epoch 115/1000
5414/5414 [==============================] - 0s 13us/sample - loss: 0.4516 - accuracy: 0.7802 - val_loss: 0.4871 - val_accuracy: 0.7820
Epoch 116/1000
5414/5414 [==============================] - 0s 12us/sample - loss: 0.4637 - accuracy: 0.7885 - val_loss: 0.5301 - val_accuracy: 0.7984
Epoch 117/1000
5414/5414 [==============================] - 0s 14us/sample - loss: 0.5002 - accuracy: 0.7878 - val_loss: 0.5506 - val_accuracy: 0.7639
Epoch 118/1000
5414/5414 [==============================] - 0s 15us/sample - loss: 0.4945 - accuracy: 0.7867 - val_loss: 0.5257 - val_accuracy: 0.7889
Epoch 119/1000
5414/5414 [==============================] - 0s 23us/sample - loss: 0.4734 - accuracy: 0.7920 - val_loss: 0.5455 - val_accuracy: 0.7587
Epoch 120/1000
5414/5414 [==============================] - 0s 19us/sample - loss: 0.4757 - accuracy: 0.7841 - val_loss: 0.5164 - val_accuracy: 0.8048
Epoch 121/1000
5414/5414 [==============================] - 0s 14us/sample - loss: 0.4656 - accuracy: 0.7918 - val_loss: 0.4835 - val_accuracy: 0.7760
Epoch 122/1000
5414/5414 [==============================] - 0s 13us/sample - loss: 0.4588 - accuracy: 0.7854 - val_loss: 0.5382 - val_accuracy: 0.7501
Epoch 123/1000
5414/5414 [==============================] - 0s 12us/sample - loss: 0.4967 - accuracy: 0.7433 - val_loss: 0.4754 - val_accuracy: 0.7415
Epoch 124/1000
5414/5414 [==============================] - 0s 13us/sample - loss: 0.4552 - accuracy: 0.7883 - val_loss: 0.4485 - val_accuracy: 0.8143

C:\Users\ASUS\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  This is separate from the ipykernel package so we can avoid doing imports until

In [93]:
print("Train time: {} ".format(end-start))

Train time: 10.95967029999997

In [94]:
predicted = model.predict(X_test)

In [95]:
model.metrics_names

['loss', 'accuracy']

In [96]:
# ini untuk cek akurasi dari data test

In [97]:
model.evaluate(x=X_test,y=y_test)

2321/2321 [==============================] - 0s 56us/sample - loss: 0.4220 - accuracy: 0.8109

[0.4220458626464645, 0.8108574]